version: "3.7"

services:

    postgres:
        image: "postgres:12-alpine"
        volumes:
            - "postgres-data:/var/lib/postgresql/data"

    app:
        build:
            context: "./app"
            dockerfile: "Dockerfile"
        depends_on:
          - "postgres"
        ports:
            - "3001:3000"
        volumes:
            - "./app:/home/node/app"

    cli:
        build:
            context: "./cli"
            dockerfile: "Dockerfile"
        depends_on:
          - "app"
        ports:
            - "3000:3000"
        volumes:
            - "./cli:/home/node/app"

volumes:

    postgres-data: {}
